version: '3.3'

services:
    postgres:
        build: ./docker/postgres
        ports:
            - 15432:5432
        environment:
            POSTGRES_DB: testdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
