version: '3.3'

services:
    postgres:
        build: ./docker/postgres
        ports:
            - 15432:5432
        environment:
            # 1_testdb_ddl.sql内でCREATE DATABASEするのでこっちはコメントアウト
            # POSTGRES_DB: testdb
            # 以下の環境変数2つについてDockerfile内でPGTDEのセットアップするときに
            # postgres/postgresで決め打ちしてるので変えないこと
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
